# Generated by Django 5.0.2 on 2024-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_word', models.CharField(help_text='Enter a vocabulary word for this flashcard', max_length=25)),
                ('example_sentence', models.TextField(blank=True, help_text='Enter an example sentence for the vocabulary word')),
                ('vocab_answer', models.TextField(help_text='Insert one or more definition(s), translation(s), etc. for your vocabulary word')),
                ('num_times_correct', models.IntegerField(default=0)),
                ('num_times_wrong', models.IntegerField(default=0)),
                ('correct_streak', models.IntegerField(default=0)),
                ('days_until_next_study', models.IntegerField(default=0, help_text='Enter an integer representing the number of days until you want to study this card again.')),
                ('date_last_studied', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-vocab_word'],
            },
        ),
    ]
