# Generated by Django 5.0.2 on 2024-02-26 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularycard",
            name="last_app_activity_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vocabularycard",
            name="last_card_activity_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vocabularycard",
            name="date_last_studied",
            field=models.DateTimeField(default=None),
        ),
    ]
