# Generated by Django 5.0.2 on 2024-02-26 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_vocabularycard_last_app_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabularycard",
            name="date_last_studied",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
